<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

add_action( 'genesis_after_header', 'hero_post_page_search' );
function hero_post_page_search() {
    ?>
    
<?php
}

add_action( 'genesis_before_loop', 'genesis_do_search_title' );
/**
 * Echo the title with the search term.
 *
 * @since 1.9.0
 */
function genesis_do_search_title() {

	$title = sprintf( '<div class="archive-description title-search"><h1 class="archive-title">%s %s</h1></div>', apply_filters( 'genesis_search_title_text', __( 'Search Results for:', 'genesis' ) ), get_search_query() );

    echo apply_filters( 'genesis_search_title_output', $title ) . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
}

add_filter( 'genesis_pre_get_option_site_layout', '__genesis_return_full_width_content' );
add_action( 'genesis_before_loop', 'genesis_posts_nav' );
/* Remove the default loop */
remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_loop', 'sk_do_search_loop' );
/**
 * Outputs a custom loop.
 *
 * @global mixed $paged current page number if paginated.
 * @return void
 */
function sk_do_search_loop() { ?>
<?php
// create an array variable with specific post types in your desired order.
	$post_typess = array('product' );
	echo '<div class="search-content">';
	$a = 0;
	global $paged, $page;
	$paged = ( get_query_var('paged') ) ? get_query_var('paged') : 1;
	foreach ( $post_typess as $post_type ) {
		// get the search term entered by user.
		$s = isset( $_GET["s"] ) ? $_GET["s"] : "";
		// accepts any wp_query args.
		$search_query = (array(
			's' => $s,
			'post_type' => $post_type,
			'showposts' => -1,
			'order' => 'ASC',
			'orderby' => 'title'
			//'paged'   => $paged
		));
		$cwp_query = new WP_Query( $search_query );
		if ( $cwp_query->have_posts() ) {
			//echo '<div class="post-type '. $post_type .'"><div class="post-type-heading"> Results in <strong>'.  $post_type . '</strong></div><hr>';
				// remove post info.
				remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );
				// remove post image (from theme settings).
				remove_action( 'genesis_entry_content', 'genesis_do_post_image', 8 );
				// remove entry content.
				
				// remove_action( 'genesis_entry_content', 'genesis_do_post_content' );
				// remove post content nav.
				remove_action( 'genesis_entry_content', 'genesis_do_post_content_nav', 12 );
				remove_action( 'genesis_entry_content', 'genesis_do_post_permalink', 14 );
				// Entry content.
				add_filter( 'genesis_before_entry_content', 'genesis_do_post_title' );
				add_filter( 'genesis_entry_content', 'featured_post_image', 8 );
				// force content limit.
				add_filter( 'genesis_pre_get_option_content_archive_limit', 'sk_content_limit' );
				// modify the Content Limit read more link.
				add_filter( 'get_the_content_more_link', 'sp_read_more_link' );
				// force excerpts.
				// add_filter( 'genesis_pre_get_option_content_archive', 'sk_show_excerpts' );
				// modify the Excerpt read more link.
				add_filter( 'excerpt_more', 'new_excerpt_more' );
				//add_filter( 'genesis_entry_content', 'file_under' );
				
				// modify the length of post excerpts.
				add_filter( 'excerpt_length', 'sp_excerpt_length' );
				// remove entry footer.
				// remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_open', 5 );
				// remove_action( 'genesis_entry_footer', 'genesis_entry_footer_markup_close', 15 );
				// remove_action( 'genesis_entry_footer', 'genesis_post_meta' );
				// remove archive pagination.
				//remove_action( 'genesis_after_endwhile', 'genesis_posts_nav' );
				// custom genesis loop with the above query parameters and hooks.
				genesis_custom_loop( $search_query );

			//echo '</div>';
		}else{
			/*$a++;
			if($a>=2  ){
				echo'<h2> Sorry, no content matched your criteria.</h2>'; 
				echo '<img style="max-width: 200px;margin: 0 auto;display: block;" src="'.get_stylesheet_directory_uri().'/images/unhappy.png" alt="image" />' ?>
			<?php
			}*/
		}
		
	}
		
	echo '</div>'; // .search-content
}
function file_under() {
	if ( get_post_type( get_the_ID() ) == 'reviews' ):
		echo '<p class="entry-meta"><span class="entry-categories">Filed Under: <a href="'. get_permalink() .'">'. get_post_type( get_the_ID()) .'</a></span></p><hr>';
	endif;
}

function sk_content_limit() {
	return '200'; // number of characters.
}
function sp_read_more_link() {
	return ''.get_post_meta(get_the_ID(), '_yoast_wpseo_metadesc', true).'... <br> <a class="arrow-link d-inline-block mt-4" href="' . get_permalink() . '">Continue Reading</a> ' .  $post_type . '';
	echo get_post_meta(get_the_ID(), '_yoast_wpseo_metadesc', true);
}
function sk_show_excerpts() {
	return 'excerpts';
}
function new_excerpt_more( $more ) {
	return '... <br> <a class="arrow-link d-inline-block mt-4" href="' . get_permalink() . '">Continue Reading</a>';
}
function sp_excerpt_length( $length ) {
	return 20; // pull first 20 words.
}

function featured_post_image() {
	echo '<div>';
	echo '<a href=" '. get_the_permalink() .' ">';	 
		$preview_image = get_field('preview_image');
		if($preview_image){
			echo '<img src="'. get_stylesheet_directory_uri() .'/images/loupe.png" alt="" />';
		}
		elseif(has_post_thumbnail()){
			echo '<div class="featured-img" style="background:url('.get_the_post_thumbnail_url().');background-repeat:no-repeat;background-size: 100% auto;background-position:center;"></div>';
			
		}else{
			?>
				<img src="<?php echo get_stylesheet_directory_uri() ?>/images/no-image.jpg" alt="" />
			<?php
		}
	echo '</a></div>';
}

genesis();
